@HorrorTracker.Api_HostAddress = http://localhost:5116

GET {{HorrorTracker.Api_HostAddress}}/api/health
Accept: application/json

###

GET {{HorrorTracker.Api_HostAddress}}/api/catalog
Accept: application/json

###

GET {{HorrorTracker.Api_HostAddress}}/api/catalog/movie
Accept: application/json

###

GET {{HorrorTracker.Api_HostAddress}}/api/auth
Accept: application/json
